export const CONTACT_LIST ="Contacts"
export const CONTACT_DETAIL ="Contacts Detail"
export const CREATE_CONTACT ="Create Contact"
export const SETTINGS ="Settings"
export const LOGIN ="Login"
export const REGISTER ="Resgister"
export const HOME_NAVIGATOR ="Home"